name: Deploy to GitHub Pages

on:
  push:
    branches: 'guc'

jobs:
  build_site:
    runs-on: ubuntu-latest

    steps:
# Begin install guc
      - name: Set up USD binaries
        run: |
          export USD_INSTALL=/home/runner/work/USD/USD/INSTALL
          curl "https://github.com/pablode/USD/releases/download/v24.03-ci-release2/USD24.03_Linux_x64.tar.gz" -L -v -o USD.tar.gz
          mkdir -p $USD_INSTALL && tar -xvf USD.tar.gz -C $USD_INSTALL
          echo "LD_LIBRARY_PATH=$USD_INSTALL/lib" >> $GITHUB_ENV
          echo "$USD_INSTALL/bin" >> $GITHUB_PATH
          echo "USD_INSTALL=$USD_INSTALL" >> $GITHUB_ENV

      - name: Check out guc
        uses: actions/checkout@v4
        with:
          repository: pablode/guc
          submodules: true
          ref: dev

      - name: Create guc folders
        run: mkdir BUILD INSTALL

      - name: Install guc
        working-directory: BUILD
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release -j 2
          cmake --install . --config Release --component guc
          echo "$PWD/bin" >> $GITHUB_PATH

      - name: Print guc help
        run: guc -h || [ $? -eq 1 ]
# End install guc

      - name: Checkout
        uses: actions/checkout@v3
        with:
          # could also be 'recursive'
          submodules: true

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          # '/asset-explorer' - not used since custom domain
          BASE_PATH: ''
        run: |
          npm run build
          touch build/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1